version: '3.6'

services:
  simplerisk:
    image: docker.io/simplerisk/simplerisk-minimal:20260828-001
    env_file: .env
    environment:
      - DB_SETUP=automatic
      - SIMPLERISK_DB_HOSTNAME=mysql
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - mysql

  mysql:
    image: docker.io/library/mysql:8.0
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    env_file: .env

  smtp:
    image: docker.io/namshi/smtp
